version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "moonthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "moonthly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "moonthly"
